dist: trusty
os:
  - linux

language: node_js
node_js:
  - '9'
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

stages:
  - test
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)

install: travis_retry npm install

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_OS_NAME
        - node --version
        - npm --version
        - ng --version
        - npm test

    - stage: deploy
      script:
        - echo "Packing NgModule ..."
        - npm run ng:packagr
        - echo "Deploying to NPM ..."

      before_deploy:
        - cd dist/

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
