dist: trusty
os:
  - linux

language: node_js
node_js:
  - '9'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

stages:
  - test
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

install: travis_retry npm install

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_OS_NAME
        - node --version
        - npm --version
        - ng --version
        - npm test

    - stage: deploy
      script:
        - echo "Packing NgModule ..."
        - if ./scripts/development-release.ts; then ./scripts/package-publish-config-tag-next.ts; fi
        - npm run ng:packagr
        - echo "Deploying to NPM ..."

      before_deploy:
        - cd dist/

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
