dist: trusty
os:
  - linux

language: node_js
node_js:
  - '6'
  - '7'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm run lint
  - npm run dist
  - npm test

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: dev@chatie.io
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
